# Generated by Django 6.1 on 2026-08-17 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_location', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFICATION', 'Verification'), ('COMMITTEE_REVIEW', 'Committee Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('institution_type', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_study', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_number', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('income_category', models.CharField(blank=True, max_length=100, null=True)),
                ('vulnerability_status', models.TextField(blank=True, null=True)),
                ('fee_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_support', models.BooleanField(default=False)),
                ('previous_support_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fraud_score', models.CharField(default='LOW_RISK', max_length=20)),
                ('eligibility_score', models.IntegerField(blank=True, null=True)),
                ('awarded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
