# Generated by Django 6.1 on 2026-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/admission/'),
        ),
        migrations.AddField(
            model_name='application',
            name='fee_structure',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/fee/'),
        ),
        migrations.AddField(
            model_name='application',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/id/'),
        ),
    ]
