# Generated by Django 6.1 on 2026-08-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_admission_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BursaryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(default='2026/2027', max_length=20, unique=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=20000000.0, max_digits=12)),
            ],
        ),
    ]
