# Generated by Django 5.2.13 on 2026-08-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_bursarybudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='polling_station',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ward',
            field=models.CharField(blank=True, choices=[('Emali/Mulala', 'Emali/Mulala'), ('Makindu', 'Makindu'), ('Nguu/Masumba', 'Nguu/Masumba'), ('Nguumo', 'Nguumo'), ('Kikumbulyu North', 'Kikumbulyu North'), ('Kikumbulyu South', 'Kikumbulyu South')], max_length=100, null=True),
        ),
    ]
