# Generated by Django 6.1 on 2026-08-17 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='bursary_documents/%Y/%m/%d/')),
                ('file_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(default='PENDING', max_length=50)),
                ('ocr_status', models.CharField(default='NOT_SCANNED', max_length=50)),
                ('ocr_extracted_text', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
        ),
    ]
