export const INITIAL_DATA = {
  activeCycle: {
    id: 1,
    title: "2026/2027 Financial Year (Cycle 1)",
    academic_year: "2026/2027",
    total_budget: 30000000.0,
    allocated_amount: 0.0,
    disbursed_amount: 0.0,
    start_date: "2026-06-01",
    end_date: "2026-09-30",
    status: "committee_review",
  },
  wards: [
    { id: 1, name: "Emali / Mulala Ward", code: "KBW-01", population: 45000, budget_allocation: 5500000.0, representative_name: "Hon. Francis Musyoka" },
    { id: 2, name: "Nguu / Masumba Ward", code: "KBW-02", population: 38000, budget_allocation: 5000000.0, representative_name: "Hon. Daniel Kimanzi" },
    { id: 3, name: "Nguumo Ward", code: "KBW-03", population: 42000, budget_allocation: 5200000.0, representative_name: "Hon. Geoffrey Musyoki" },
    { id: 4, name: "Makindu Ward", code: "KBW-04", population: 52000, budget_allocation: 6000000.0, representative_name: "Hon. Jackson Muthama" },
    { id: 5, name: "Kikumbulyu North Ward", code: "KBW-05", population: 36000, budget_allocation: 4800000.0, representative_name: "Hon. Onesmus Mutinda" },
    { id: 6, name: "Kikumbulyu South Ward", code: "KBW-06", population: 39000, budget_allocation: 5000000.0, representative_name: "Hon. Peter Mwololo" },
  ],
  institutions: [
    { id: 1, name: "University of Nairobi (UoN)", code: "UON-001", type: "university", county: "Nairobi", bank_name: "KCB Bank", bank_account_no: "1100234567" },
    { id: 2, name: "Kenyatta University (KU)", code: "KU-002", type: "university", county: "Nairobi", bank_name: "National Bank", bank_account_no: "0100345678" },
    { id: 3, name: "Kabete National Polytechnic", code: "KABETE-003", type: "tvet", county: "Nairobi", bank_name: "Equity Bank", bank_account_no: "0550123456" },
    { id: 4, name: "Nairobi Technical Training Institute", code: "NTTI-004", type: "tvet", county: "Nairobi", bank_name: "Co-operative Bank", bank_account_no: "0112987654" },
    { id: 5, name: "Dagoretti High School", code: "DAG-005", type: "secondary", county: "Nairobi", bank_name: "KCB Bank", bank_account_no: "1122334455" },
    { id: 6, name: "Kenya Medical Training College (KMTC)", code: "KMTC-006", type: "tvet", county: "Nairobi", bank_name: "National Bank", bank_account_no: "0100998877" },
    { id: 7, name: "Strathmore University", code: "STRATH-007", type: "university", county: "Nairobi", bank_name: "Standard Chartered", bank_account_no: "0102030405" },
    { id: 8, name: "St. Francis Special Needs School", code: "STF-008", type: "special_needs", county: "Nairobi", bank_name: "Co-operative Bank", bank_account_no: "0110332211" },
  ],
  demoUsers: [
    { id: 1, name: "Willy", role: "admin", designation: "Constituency Fund Manager / Super Admin", email: "admin@ngcdf.go.ke", national_id: "41354126" },
  ],
  applications: [],
  auditLogs: [],
  statistics: {
    total_applications: 0,
    verified_applications: 0,
    committee_recommended: 0,
    approved_beneficiaries: 0,
    total_budget: 30000000.0,
    allocated_amount: 0.0,
    disbursed_amount: 0.0,
  }
};

export const initialApplications = INITIAL_DATA.applications;
export const initialWards = INITIAL_DATA.wards;
export const initialInstitutions = INITIAL_DATA.institutions;
export const initialAuditLogs = INITIAL_DATA.auditLogs;
export const initialStatistics = INITIAL_DATA.statistics;
export const initialUsers = INITIAL_DATA.demoUsers;

// =================================================================
// ACCREDITED KENYA INSTITUTIONS MASTER REGISTRY (CUE, TVETA, MOE, KMTC)
// =================================================================
export const KENYA_INSTITUTIONS_REGISTRY = [
  // 1. PUBLIC UNIVERSITIES
  { name: "University of Nairobi (UoN)", type: "university", code: "UON-001", county: "Nairobi", address: "P.O. Box 30197 - 00100, Nairobi, Kenya", campus: "Main Campus, University Way", email: "finance@uonbi.ac.ke" },
  { name: "Kenyatta University (KU)", type: "university", code: "KU-002", county: "Nairobi", address: "P.O. Box 43844 - 00100, Nairobi, Kenya", campus: "Main Campus, Along Thika Superhighway", email: "finance@ku.ac.ke" },
  { name: "Jomo Kenyatta University of Agriculture and Technology (JKUAT)", type: "university", code: "JKUAT-003", county: "Kiambu", address: "P.O. Box 62000 - 00200, Nairobi, Kenya", campus: "Main Campus, Juja", email: "finance@jkuat.ac.ke" },
  { name: "Moi University", type: "university", code: "MU-004", county: "Uasin Gishu", address: "P.O. Box 3900 - 30100, Eldoret, Kenya", campus: "Main Campus, Kesses, Eldoret", email: "finance@mu.ac.ke" },
  { name: "Egerton University", type: "university", code: "EU-005", county: "Nakuru", address: "P.O. Box 536 - 20115, Egerton, Njoro, Kenya", campus: "Main Campus, Njoro", email: "finance@egerton.ac.ke" },
  { name: "Maseno University", type: "university", code: "MSU-006", county: "Kisumu", address: "Private Bag, Maseno - 40105, Kenya", campus: "Main Campus, Maseno", email: "finance@maseno.ac.ke" },
  { name: "Masinde Muliro University of Science and Technology (MMUST)", type: "university", code: "MMUST-007", county: "Kakamega", address: "P.O. Box 190 - 50100, Kakamega, Kenya", campus: "Main Campus, Kakamega", email: "finance@mmust.ac.ke" },
  { name: "Technical University of Kenya (TUK)", type: "university", code: "TUK-008", county: "Nairobi", address: "P.O. Box 52428 - 00200, Nairobi, Kenya", campus: "Haile Selassie Avenue, Nairobi", email: "finance@tukenya.ac.ke" },
  { name: "Technical University of Mombasa (TUM)", type: "university", code: "TUM-009", county: "Mombasa", address: "P.O. Box 90420 - 80100, Mombasa, Kenya", campus: "Tudor, Tom Mboya Avenue, Mombasa", email: "finance@tum.ac.ke" },
  { name: "Machakos University", type: "university", code: "MKSU-010", county: "Machakos", address: "P.O. Box 136 - 90100, Machakos, Kenya", campus: "Main Campus, Machakos Town", email: "finance@mksu.ac.ke" },
  { name: "South Eastern Kenya University (SEKU)", type: "university", code: "SEKU-011", county: "Kitui", address: "P.O. Box 170 - 90200, Kitui, Kenya", campus: "Main Campus, Kwa Vonza", email: "finance@seku.ac.ke" },
  { name: "Dedan Kimathi University of Technology (DeKUT)", type: "university", code: "DEKUT-012", county: "Nyeri", address: "P.O. Box 657 - 10100, Nyeri, Kenya", campus: "Main Campus, Nyeri-Mweiga Road", email: "finance@dkut.ac.ke" },
  { name: "Chuka University", type: "university", code: "CHUKA-013", county: "Tharaka Nithi", address: "P.O. Box 109 - 60400, Chuka, Kenya", campus: "Main Campus, Ndagani, Chuka", email: "finance@chuka.ac.ke" },
  { name: "Kisii University", type: "university", code: "KSU-014", county: "Kisii", address: "P.O. Box 408 - 40200, Kisii, Kenya", campus: "Main Campus, Kisii", email: "finance@kisiiuniversity.ac.ke" },
  { name: "University of Eldoret (UoE)", type: "university", code: "UOE-015", county: "Uasin Gishu", address: "P.O. Box 1125 - 30100, Eldoret, Kenya", campus: "Main Campus, Eldoret-Ziwa Road", email: "finance@uoeld.ac.ke" },
  { name: "Maasai Mara University", type: "university", code: "MMU-016", county: "Narok", address: "P.O. Box 861 - 20500, Narok, Kenya", campus: "Main Campus, Narok Town", email: "finance@mmarau.ac.ke" },
  { name: "Jaramogi Oginga Odinga University of Science and Technology (JOOUST)", type: "university", code: "JOOUST-017", county: "Siaya", address: "P.O. Box 210 - 40601, Bondo, Kenya", campus: "Main Campus, Bondo Town", email: "finance@jooust.ac.ke" },
  { name: "Laikipia University", type: "university", code: "LU-018", county: "Laikipia", address: "P.O. Box 1100 - 20300, Nyahururu, Kenya", campus: "Main Campus, Nyahururu", email: "finance@laikipia.ac.ke" },
  { name: "Meru University of Science and Technology (MUST)", type: "university", code: "MUST-019", county: "Meru", address: "P.O. Box 972 - 60200, Meru, Kenya", campus: "Main Campus, Nchiru, Meru", email: "finance@must.ac.ke" },
  { name: "Multimedia University of Kenya (MMU)", type: "university", code: "MMUK-020", county: "Nairobi", address: "P.O. Box 15653 - 00503, Nairobi, Kenya", campus: "Main Campus, Magadi Road, Rongai", email: "finance@mmu.ac.ke" },
  { name: "University of Kabianga", type: "university", code: "UOK-021", county: "Kericho", address: "P.O. Box 2030 - 20200, Kericho, Kenya", campus: "Main Campus, Kabianga, Kericho", email: "finance@kabianga.ac.ke" },
  { name: "Karatina University", type: "university", code: "KARU-022", county: "Nyeri", address: "P.O. Box 1957 - 10101, Karatina, Kenya", campus: "Main Campus, Kagochi, Karatina", email: "finance@karatina.ac.ke" },
  { name: "Kibabii University", type: "university", code: "KIBU-023", county: "Bungoma", address: "P.O. Box 1699 - 50200, Bungoma, Kenya", campus: "Main Campus, Bungoma", email: "finance@kibu.ac.ke" },
  { name: "Rongo University", type: "university", code: "RU-024", county: "Migori", address: "P.O. Box 103 - 40404, Rongo, Kenya", campus: "Main Campus, Kitere Hill, Rongo", email: "finance@rongovarsity.ac.ke" },
  { name: "The Co-operative University of Kenya (CUK)", type: "university", code: "CUK-025", county: "Nairobi", address: "P.O. Box 24814 - 00502, Karen, Nairobi, Kenya", campus: "Main Campus, Ushirika Road, Karen", email: "finance@cuk.ac.ke" },
  { name: "Taita Taveta University (TTU)", type: "university", code: "TTU-026", county: "Taita Taveta", address: "P.O. Box 635 - 80300, Voi, Kenya", campus: "Main Campus, Voi", email: "finance@ttu.ac.ke" },
  { name: "Murang'a University of Technology (MUT)", type: "university", code: "MUT-027", county: "Murang'a", address: "P.O. Box 75 - 10200, Murang'a, Kenya", campus: "Main Campus, Murang'a Town", email: "finance@mut.ac.ke" },
  { name: "University of Embu", type: "university", code: "UEMBU-028", county: "Embu", address: "P.O. Box 6 - 60100, Embu, Kenya", campus: "Main Campus, Embu Town", email: "finance@embuni.ac.ke" },
  { name: "Kirinyaga University", type: "university", code: "KYU-029", county: "Kirinyaga", address: "P.O. Box 143 - 10300, Kerugoya, Kenya", campus: "Main Campus, Kutus Town", email: "finance@kyu.ac.ke" },
  { name: "Garissa University", type: "university", code: "GAU-030", county: "Garissa", address: "P.O. Box 1801 - 70100, Garissa, Kenya", campus: "Main Campus, Garissa Town", email: "finance@gau.ac.ke" },
  { name: "Alupe University", type: "university", code: "ALUPE-031", county: "Busia", address: "P.O. Box 845 - 50400, Busia, Kenya", campus: "Main Campus, Busia-Malaba Road", email: "finance@alupe.ac.ke" },
  { name: "Kaimosi Friends University", type: "university", code: "KAFU-032", county: "Vihiga", address: "P.O. Box 385 - 50309, Kaimosi, Kenya", campus: "Main Campus, Kaimosi", email: "finance@kafu.ac.ke" },
  { name: "Tom Mboya University", type: "university", code: "TMU-033", county: "Homa Bay", address: "P.O. Box 199 - 40300, Homa Bay, Kenya", campus: "Main Campus, Homa Bay Town", email: "finance@tmu.ac.ke" },
  { name: "Tharaka University", type: "university", code: "THARAKA-034", county: "Tharaka Nithi", address: "P.O. Box 70 - 60215, Marimanti, Kenya", campus: "Main Campus, Marimanti", email: "finance@tharaka.ac.ke" },
  { name: "Bomet University College", type: "university", code: "BUC-035", county: "Bomet", address: "P.O. Box 701 - 20400, Bomet, Kenya", campus: "Main Campus, Bomet Town", email: "finance@buc.ac.ke" },
  { name: "Koitaleel Samoei University College", type: "university", code: "KSUC-036", county: "Nandi", address: "P.O. Box 5 - 30307, Mosoriot, Kenya", campus: "Main Campus, Mosoriot", email: "finance@ksu.ac.ke" },
  { name: "Turkana University College", type: "university", code: "TUC-037", county: "Turkana", address: "P.O. Box 69 - 30500, Lodwar, Kenya", campus: "Main Campus, Lodwar", email: "finance@tuc.ac.ke" },

  // 2. CHARTERED PRIVATE UNIVERSITIES
  { name: "Strathmore University", type: "university", code: "STRATH-050", county: "Nairobi", address: "P.O. Box 59857 - 00200, Nairobi, Kenya", campus: "Ole Sangale Road, Madaraka", email: "finance@strathmore.edu" },
  { name: "Mount Kenya University (MKU)", type: "university", code: "MKU-051", county: "Kiambu", address: "P.O. Box 342 - 01000, Thika, Kenya", campus: "General Kago Road, Thika", email: "finance@mku.ac.ke" },
  { name: "United States International University Africa (USIU-Africa)", type: "university", code: "USIU-052", county: "Nairobi", address: "P.O. Box 14634 - 00800, Nairobi, Kenya", campus: "Off Thika Road, Behind Safari Park", email: "finance@usiu.ac.ke" },
  { name: "Catholic University of Eastern Africa (CUEA)", type: "university", code: "CUEA-053", county: "Nairobi", address: "P.O. Box 62157 - 00200, Nairobi, Kenya", campus: "Bogani East Road, Karen", email: "finance@cuea.edu" },
  { name: "Daystar University", type: "university", code: "DAYSTAR-054", county: "Machakos", address: "P.O. Box 44400 - 00100, Nairobi, Kenya", campus: "Main Campus, Lukenya, Athi River", email: "finance@daystar.ac.ke" },
  { name: "Africa Nazarene University (ANU)", type: "university", code: "ANU-055", county: "Kajiado", address: "P.O. Box 53067 - 00200, Nairobi, Kenya", campus: "Main Campus, Ongata Rongai", email: "finance@anu.ac.ke" },
  { name: "Kenya Methodist University (KeMU)", type: "university", code: "KEMU-056", county: "Meru", address: "P.O. Box 267 - 60200, Meru, Kenya", campus: "Main Campus, Meru Town", email: "finance@kemu.ac.ke" },
  { name: "St. Paul's University", type: "university", code: "SPU-057", county: "Kiambu", address: "Private Bag - 00217, Limuru, Kenya", campus: "Main Campus, Limuru", email: "finance@spu.ac.ke" },
  { name: "Kabarak University", type: "university", code: "KABARAK-058", county: "Nakuru", address: "Private Bag - 20157, Kabarak, Kenya", campus: "Main Campus, Nakuru-Eldama Ravine Hwy", email: "finance@kabarak.ac.ke" },
  { name: "KCA University", type: "university", code: "KCA-059", county: "Nairobi", address: "P.O. Box 56808 - 00200, Nairobi, Kenya", campus: "Main Campus, Ruaraka, Thika Road", email: "finance@kca.ac.ke" },
  { name: "Lukenya University", type: "university", code: "LUKENYA-060", county: "Makueni", address: "P.O. Box 90 - 90128, Mtito Andei, Kenya", campus: "Main Campus, Kambu, Kibwezi East", email: "finance@lukenyauniversity.ac.ke" },
  { name: "Zetech University", type: "university", code: "ZETECH-061", county: "Kiambu", address: "P.O. Box 2768 - 00200, Nairobi, Kenya", campus: "Main Campus, Ruiru, Along Thika Road", email: "finance@zetech.ac.ke" },
  { name: "Riara University", type: "university", code: "RIARA-062", county: "Nairobi", address: "P.O. Box 49940 - 00100, Nairobi, Kenya", campus: "Mbagathi Way, Nairobi", email: "finance@riarauniversity.ac.ke" },
  { name: "Scott Christian University", type: "university", code: "SCOTT-063", county: "Machakos", address: "P.O. Box 49 - 90100, Machakos, Kenya", campus: "Main Campus, Machakos Town", email: "finance@scott.ac.ke" },
  { name: "Umma University", type: "university", code: "UMMA-064", county: "Kajiado", address: "P.O. Box 713 - 01100, Kajiado, Kenya", campus: "Main Campus, Kajiado Town", email: "finance@umma.ac.ke" },
  { name: "Amref International University (AMIU)", type: "university", code: "AMREF-065", county: "Nairobi", address: "P.O. Box 27691 - 00506, Nairobi, Kenya", campus: "Lang'ata Road, Nairobi", email: "finance@amref.ac.ke" },

  // 3. KMTC CAMPUSES
  { name: "Kenya Medical Training College (KMTC) - Nairobi Campus", type: "college_tvet", code: "KMTC-NBI", county: "Nairobi", address: "P.O. Box 30195 - 00100, Nairobi, Kenya", campus: "Ngong Road, Nairobi", email: "info@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Makindu Campus", type: "college_tvet", code: "KMTC-MAK", county: "Makueni", address: "P.O. Box 171 - 90138, Makindu, Kenya", campus: "Makindu Sub-County Hospital Grounds", email: "makindu@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Machakos Campus", type: "college_tvet", code: "KMTC-MCK", county: "Machakos", address: "P.O. Box 838 - 90100, Machakos, Kenya", campus: "Machakos Level 5 Hospital Grounds", email: "machakos@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Kitui Campus", type: "college_tvet", code: "KMTC-KT", county: "Kitui", address: "P.O. Box 67 - 90200, Kitui, Kenya", campus: "Kitui Level 4 Hospital Grounds", email: "kitui@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Mbooni Campus", type: "college_tvet", code: "KMTC-MBN", county: "Makueni", address: "P.O. Box 56 - 90125, Kikima, Kenya", campus: "Mbooni Sub-County Hospital", email: "mbooni@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Mombasa Campus", type: "college_tvet", code: "KMTC-MSA", county: "Mombasa", address: "P.O. Box 87946 - 80100, Mombasa, Kenya", campus: "Coast General Hospital Grounds", email: "mombasa@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Nakuru Campus", type: "college_tvet", code: "KMTC-NKU", county: "Nakuru", address: "P.O. Box 110 - 20100, Nakuru, Kenya", campus: "Nakuru Level 5 Hospital Grounds", email: "nakuru@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Kisumu Campus", type: "college_tvet", code: "KMTC-KSM", county: "Kisumu", address: "P.O. Box 149 - 40100, Kisumu, Kenya", campus: "JOOTRH Grounds, Kisumu", email: "kisumu@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Eldoret Campus", type: "college_tvet", code: "KMTC-ELD", county: "Uasin Gishu", address: "P.O. Box 520 - 30100, Eldoret, Kenya", campus: "MTRH Grounds, Eldoret", email: "eldoret@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Nyeri Campus", type: "college_tvet", code: "KMTC-NYI", county: "Nyeri", address: "P.O. Box 466 - 10100, Nyeri, Kenya", campus: "Nyeri PGH Grounds", email: "nyeri@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Thika Campus", type: "college_tvet", code: "KMTC-THK", county: "Kiambu", address: "P.O. Box 729 - 01000, Thika, Kenya", campus: "Thika Level 5 Hospital Grounds", email: "thika@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Voi Campus", type: "college_tvet", code: "KMTC-VOI", county: "Taita Taveta", address: "P.O. Box 422 - 80300, Voi, Kenya", campus: "Voi Hospital Grounds", email: "voi@kmtc.ac.ke" },
  { name: "Kenya Medical Training College (KMTC) - Mutomo Campus", type: "college_tvet", code: "KMTC-MTM", county: "Kitui", address: "P.O. Box 80 - 90201, Mutomo, Kenya", campus: "Mutomo Mission Hospital Grounds", email: "mutomo@kmtc.ac.ke" },

  // 4. NATIONAL POLYTECHNICS & TVETS
  { name: "Kabete National Polytechnic", type: "college_tvet", code: "KABETE-100", county: "Nairobi", address: "P.O. Box 29010 - 00625, Nairobi, Kenya", campus: "Waiyaki Way, Nairobi", email: "info@kabetepoly.ac.ke" },
  { name: "Kenya Coast National Polytechnic", type: "college_tvet", code: "KCNP-101", county: "Mombasa", address: "P.O. Box 81220 - 80100, Mombasa, Kenya", campus: "Kisauni Road, Mombasa", email: "info@kenyacoastpoly.ac.ke" },
  { name: "Kisumu National Polytechnic", type: "college_tvet", code: "KISPOLY-102", county: "Kisumu", address: "P.O. Box 143 - 40100, Kisumu, Kenya", campus: "Technology Way, Kisumu", email: "info@kisumupoly.ac.ke" },
  { name: "Eldoret National Polytechnic", type: "college_tvet", code: "ELDPOLY-103", county: "Uasin Gishu", address: "P.O. Box 4461 - 30100, Eldoret, Kenya", campus: "Eldoret-Kapsabet Road", email: "info@tenp.ac.ke" },
  { name: "Nyeri National Polytechnic", type: "college_tvet", code: "NYERIPOLY-104", county: "Nyeri", address: "P.O. Box 465 - 10100, Nyeri, Kenya", campus: "Mumbi Road, Nyeri Town", email: "info@thenyeripoly.ac.ke" },
  { name: "Sigalagala National Polytechnic", type: "college_tvet", code: "SIGPOLY-105", county: "Kakamega", address: "P.O. Box 2966 - 50100, Kakamega, Kenya", campus: "Kakamega-Kisumu Road", email: "info@sigalagalapoly.ac.ke" },
  { name: "Meru National Polytechnic", type: "college_tvet", code: "MERUPOLY-106", county: "Meru", address: "P.O. Box 111 - 60200, Meru, Kenya", campus: "Meru-Nanyuki Highway", email: "info@merunationalpoly.ac.ke" },
  { name: "Kitale National Polytechnic", type: "college_tvet", code: "KITALEPOLY-107", county: "Trans Nzoia", address: "P.O. Box 2162 - 30200, Kitale, Kenya", campus: "Kitale-Elgon View Road", email: "info@kitalenationalpoly.ac.ke" },
  { name: "Kisii National Polytechnic", type: "college_tvet", code: "KSIIPOLY-108", county: "Kisii", address: "P.O. Box 222 - 40200, Kisii, Kenya", campus: "Kisii Town", email: "info@kisiipoly.ac.ke" },
  { name: "Makueni Technical College", type: "college_tvet", code: "MAKU-TVET-109", county: "Makueni", address: "P.O. Box 112 - 90300, Wote, Kenya", campus: "Wote Town, Makueni", email: "info@makuenitechnical.ac.ke" },
  { name: "Kibwezi Technical Training Institute", type: "college_tvet", code: "KBW-TVET-110", county: "Makueni", address: "P.O. Box 180 - 90137, Kibwezi, Kenya", campus: "Kibwezi Township, Kibwezi West", email: "kibwezitti@gmail.com" },
  { name: "Kitise Vocational Training Centre", type: "college_tvet", code: "KIT-VTC-111", county: "Makueni", address: "P.O. Box 45 - 90137, Kitise, Kenya", campus: "Kitise Centre, Kibwezi West", email: "kitisevtc@gmail.com" },
  { name: "Kathonzweni Vocational Training Centre", type: "college_tvet", code: "KAT-VTC-112", county: "Makueni", address: "P.O. Box 88 - 90302, Kathonzweni, Kenya", campus: "Kathonzweni Town", email: "kathonzwenivtc@gmail.com" },
  { name: "Nairobi Technical Training Institute", type: "college_tvet", code: "NTTI-113", county: "Nairobi", address: "P.O. Box 30039 - 00100, Nairobi, Kenya", campus: "Ngara, Nairobi", email: "info@nairobitti.ac.ke" },
  { name: "Railway Training Institute (RTI)", type: "college_tvet", code: "RTI-114", county: "Nairobi", address: "P.O. Box 56708 - 00200, Nairobi, Kenya", campus: "South B, Nairobi", email: "info@rti.ac.ke" },
  { name: "Kenya Institute of Mass Communication (KIMC)", type: "college_tvet", code: "KIMC-115", county: "Nairobi", address: "P.O. Box 42422 - 00100, Nairobi, Kenya", campus: "South B, Nairobi", email: "info@kimc.ac.ke" },
  { name: "Kenya Utalii College", type: "college_tvet", code: "KUC-116", county: "Nairobi", address: "P.O. Box 31052 - 00600, Nairobi, Kenya", campus: "Thika Road, Ruaraka", email: "info@utalii.ac.ke" },
  { name: "Kiambu Institute of Science and Technology (KIST)", type: "college_tvet", code: "KIST-117", county: "Kiambu", address: "P.O. Box 414 - 00900, Kiambu, Kenya", campus: "Kiambu Town", email: "info@kist.ac.ke" },
  { name: "Machakos Technical Institute for the Blind", type: "special_needs", code: "MTIB-118", county: "Machakos", address: "P.O. Box 128 - 90100, Machakos, Kenya", campus: "Machakos Town", email: "info@mtib.ac.ke" },
  { name: "PC Kinyanjui Technical Training Institute", type: "college_tvet", code: "PCK-119", county: "Nairobi", address: "P.O. Box 21280 - 00505, Nairobi, Kenya", campus: "Riruta, Nairobi", email: "info@kinyanjuitti.ac.ke" },
  { name: "Coast Institute of Technology", type: "college_tvet", code: "CIT-120", county: "Taita Taveta", address: "P.O. Box 34 - 80300, Voi, Kenya", campus: "Voi Town", email: "info@cit.ac.ke" },

  // 5. SECONDARY SCHOOLS (LOCAL KIBWEZI WEST / MAKUENI & TOP NATIONAL)
  { name: "Makueni Boys High School", type: "secondary", code: "MAK-SEC-200", county: "Makueni", address: "P.O. Box 102 - 90300, Wote, Kenya", campus: "Wote, Makueni County" },
  { name: "Makindu Girls Secondary School", type: "secondary", code: "MAK-GIRLS-201", county: "Makueni", address: "P.O. Box 54 - 90138, Makindu, Kenya", campus: "Makindu Town, Kibwezi West" },
  { name: "Kibwezi Secondary School", type: "secondary", code: "KBW-SEC-202", county: "Makueni", address: "P.O. Box 128 - 90137, Kibwezi, Kenya", campus: "Kibwezi Township, Kibwezi West" },
  { name: "Kikumbulyu Secondary School", type: "secondary", code: "KIK-SEC-203", county: "Makueni", address: "P.O. Box 78 - 90137, Kibwezi, Kenya", campus: "Kikumbulyu, Kibwezi West" },
  { name: "Emali Secondary School", type: "secondary", code: "EMA-SEC-204", county: "Makueni", address: "P.O. Box 45 - 90121, Emali, Kenya", campus: "Emali Township, Kibwezi West" },
  { name: "Mulala Secondary School", type: "secondary", code: "MUL-SEC-205", county: "Makueni", address: "P.O. Box 22 - 90121, Emali, Kenya", campus: "Mulala Ward, Kibwezi West" },
  { name: "Nguumo Secondary School", type: "secondary", code: "NGU-SEC-206", county: "Makueni", address: "P.O. Box 110 - 90138, Makindu, Kenya", campus: "Nguumo Ward, Kibwezi West" },
  { name: "Masumba Secondary School", type: "secondary", code: "MAS-SEC-207", county: "Makueni", address: "P.O. Box 83 - 90138, Makindu, Kenya", campus: "Nguu/Masumba Ward, Kibwezi West" },
  { name: "Kathyaka Secondary School", type: "secondary", code: "KAT-SEC-208", county: "Makueni", address: "P.O. Box 92 - 90137, Kibwezi, Kenya", campus: "Kibwezi West" },
  { name: "Kinyambu Secondary School", type: "secondary", code: "KIN-SEC-209", county: "Makueni", address: "P.O. Box 66 - 90137, Kibwezi, Kenya", campus: "Kibwezi West" },
  { name: "Kalulini Boys Secondary School", type: "secondary", code: "KAL-SEC-210", county: "Makueni", address: "P.O. Box 34 - 90137, Kibwezi, Kenya", campus: "Kikumbulyu, Kibwezi West" },
  { name: "St. Joseph's Girls Secondary School Kibwezi", type: "secondary", code: "STJ-SEC-211", county: "Makueni", address: "P.O. Box 55 - 90137, Kibwezi, Kenya", campus: "Kibwezi Town, Kibwezi West" },
  { name: "Machinery Secondary School", type: "secondary", code: "MAC-SEC-212", county: "Makueni", address: "P.O. Box 40 - 90137, Kibwezi, Kenya", campus: "Machinery, Kibwezi West" },
  { name: "Utithi Secondary School", type: "secondary", code: "UTI-SEC-213", county: "Makueni", address: "P.O. Box 19 - 90137, Kibwezi, Kenya", campus: "Kibwezi West" },
  { name: "Precious Blood Secondary School Kilungu", type: "secondary", code: "PB-SEC-214", county: "Makueni", address: "P.O. Box 1 - 90130, Nunguni, Kenya", campus: "Kilungu, Makueni County" },
  { name: "Makueni Girls High School", type: "secondary", code: "MAKG-SEC-215", county: "Makueni", address: "P.O. Box 115 - 90300, Wote, Kenya", campus: "Wote, Makueni County" },
  { name: "Alliance High School", type: "secondary", code: "ALLIANCE-300", county: "Kiambu", address: "P.O. Box 7 - 00902, Kikuyu, Kenya", campus: "Kikuyu, Kiambu" },
  { name: "Alliance Girls High School", type: "secondary", code: "ALLIANCEG-301", county: "Kiambu", address: "P.O. Box 109 - 00902, Kikuyu, Kenya", campus: "Kikuyu, Kiambu" },
  { name: "Mang'u High School", type: "secondary", code: "MANGU-302", county: "Kiambu", address: "P.O. Box 410 - 01000, Thika, Kenya", campus: "Thika Road, Kiambu" },
  { name: "Kenya High School", type: "secondary", code: "KENYAHIGH-303", county: "Nairobi", address: "P.O. Box 30035 - 00100, Nairobi, Kenya", campus: "Kileleshwa, Nairobi" },
  { name: "Starehe Boys' Centre and School", type: "secondary", code: "STAREHE-304", county: "Nairobi", address: "P.O. Box 30178 - 00100, Nairobi, Kenya", campus: "General Waruinge Street, Nairobi" },
  { name: "Lenana School", type: "secondary", code: "LENANA-305", county: "Nairobi", address: "P.O. Box 30385 - 00100, Nairobi, Kenya", campus: "Ngong Road, Nairobi" },
  { name: "Nairobi School", type: "secondary", code: "NAISCH-306", county: "Nairobi", address: "P.O. Box 30047 - 00100, Nairobi, Kenya", campus: "Waiyaki Way, Nairobi" },
  { name: "Maryhill Girls High School", type: "secondary", code: "MARYHILL-307", county: "Kiambu", address: "P.O. Box 9 - 01000, Thika, Kenya", campus: "Thika, Kiambu" },
  { name: "Maranda High School", type: "secondary", code: "MARANDA-308", county: "Siaya", address: "P.O. Box 120 - 40601, Bondo, Kenya", campus: "Bondo, Siaya" },
  { name: "Maseno School", type: "secondary", code: "MASENOSCH-309", county: "Kisumu", address: "Private Bag, Maseno - 40105, Kenya", campus: "Maseno, Kisumu" },
  { name: "Kapsabet High School", type: "secondary", code: "KAPSABET-310", county: "Nandi", address: "P.O. Box 3 - 30300, Kapsabet, Kenya", campus: "Kapsabet Town, Nandi" },

  // 6. SPECIAL NEEDS INSTITUTIONS
  { name: "St. Francis Special Needs School", type: "special_needs", code: "STF-400", county: "Nairobi", address: "P.O. Box 24814 - 00502, Karen, Nairobi, Kenya", campus: "Karen, Nairobi" },
  { name: "Machakos School for the Blind", type: "special_needs", code: "MSB-401", county: "Machakos", address: "P.O. Box 128 - 90100, Machakos, Kenya", campus: "Machakos Town" },
  { name: "Joytown Special Primary & Secondary School Thika", type: "special_needs", code: "JOYTOWN-402", county: "Kiambu", address: "P.O. Box 243 - 01000, Thika, Kenya", campus: "Thika Town" },
  { name: "Kuja Special School for the Deaf", type: "special_needs", code: "KUJA-403", county: "Migori", address: "P.O. Box 144 - 40404, Rongo, Kenya", campus: "Rongo, Migori" }
];
